version: '3'

services:
  # backend ---------------------------------------------
  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    environment:
      - MODE=dev
  
  # frontend --------------------------------------------
  frontend:
    container_name: frontend
    build:
      context: ./docker
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - MODE=dev
    depends_on:
      - backend
  
  # elastic stack ----------------------------------------
  # security diabled during dev
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  #kibana
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

# networks
networks:
  es-net:
    driver: bridge
